---
title: "DSiR00"
author: "Robert A. Stevens"
date: "March 8, 2016"
output: html_document
---

**TODO:**

1. Finish outline

2. Add R code

3. Run R code and check

4. Do exercises

*Data Science in R: A Case Studies Approach to Computational Reasoning and Problem Solving*

by Deborah Nolan and Duncan Temple Lang

http://www.rdatasciencecases.org

## Chapter 3. Using Statistics to Identify Spam 

by Deborah Nolan and Duncan Temple Lang

3.1 Introduction

3.1.1 Computational Topics

3.2 Anatomy of an email Message

3.3 Reading the email Messages

3.4 Text Mining and Naive Bayes Classification

3.5 Finding the Words in a Message

3.5.1 Splitting the Message into Its Header and Body

3.5.2 Removing Attachments from the Message Body

3.5.3 Extracting Words from the Message Body

3.5.4 Completing the Data Preparation Process

3.6 Implementing the Naive Bayes Classifier

3.6.1 Test and Training Data

3.6.2 Probability Estimates from Training Data

3.6.3 Classifying New Messages

Figure 3.1: Boxplot of Log Likelihood Ratio for Spam and Ham. The log likelikhood ration, log(P(spam | message content)/P(ham | message content)), for 3116 test messages was computed using a naive Bayes approximation based on word frequencies found in manually classified training data. The test messages are grouped according to whether they are spam or ham. Notice most ham messages have value well below 0 and nearly all spam values are above 0.

Figure 3.2: Comparison of Type I and II Error Rates. The Type I and II error rates for the 3116 test messages are show as a function of the threshold tau. For example, with a threshold of tau = -43, all messages with an LLR value above -43 are classified as spam and those below as ham. In this case, 1% of ham is misclassified as spam and 2% of spam is misclassified as ham.

3.6.4 Computational Considerations

3.7 Recursive Partitioning and Classification Trees

Figure 3.3: Example Tree from a Recursive Partition. This tree is a simple example of a recursive partition fitted model. It was fitted using the rpart() function and restricting the tree depth to 3 levels. The first yes-no question is whether the percentage of capitals in the message is less than 13. If not, the second question is whether there are fewer than 289 characters in the message. If the answer to this question is also no, then the next question is whether the message header contains an InReplyTo key. If the answer is again no, then the message is classified as spam. Of the 6232 messages in the training set, 77 ham and 643 spam fall into this leaf. The spam have been correctly classified and the 77 ham have been misclassified.

3.8 Organizing an email Message into an R Data Structure

3.8.1 Processing the Header

3.8.2 Processing Attachments

3.8.3 Testing Our Code on More email Data

3.8.4 Completing the Process

3.9 Deriving Variables from the email Message

Table 3.1: Variable Definition Table

3.9.1 Checking Our Code for Errors

Figure 3.4:

3.10 Exploring the email Feature Set

3.11 Fitting the rpart() Model to the email Data

3.12 Exercises
